/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/statutory-actions/{statActionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the statutory action. */
                statActionId: number;
            };
            cookie?: never;
        };
        /**
         * Get statutory action with parcels
         * @description Retrieve a statutory action record and its associated parcel collection.
         *     Returns statutory action metadata plus all parcel records with read-only server-managed fields.
         */
        get: operations["getStatutoryAction"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Bulk update parcels (create, update, delete)
         * @description Atomically apply a batch of parcel operations (create, update, delete)
         *     and optionally update statutory action metadata for the action identified by statActionId.
         *     This endpoint is designed to support full-form UX patterns where users can:
         *     - Update statutory action metadata (type, status, gazette fields, etc.)
         *     - Add new parcel rows (create operations)
         *     - Edit existing parcel cells (update operations)
         *     - Remove parcel rows (delete operations)
         *
         *     Then submit the entire form in one PATCH request.
         *
         *     The endpoint processes statutory action updates and all parcel rows in order,
         *     returning per-row results and metadata update confirmation.
         */
        patch: operations["patchStatutoryAction"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        PatchParcelsRequest: {
            /** @description Type/category of the statutory action (optional update) */
            statutoryActionType?: string | null;
            /** @description Current lifecycle status of the statutory action (optional update) */
            status?: string | null;
            /** @description Gazette publication year associated with the action (optional update) */
            gazetteYear?: string | null;
            /** @description Gazette page number (optional update) */
            gazettePage?: number | null;
            /** @description Gazette publication type (optional update) */
            gazetteType?: string | null;
            /** @description Additional legal basis text for the action (optional update) */
            otherLegality?: string | null;
            /** @description Gazette notice identifier (optional update) */
            gazetteNoticeId?: number | null;
            /** @description Array of parcel operations (create, update, or delete) */
            rows: components["schemas"]["ParcelRow"][];
        };
        ParcelRow: components["schemas"]["CreateParcelRow"] | components["schemas"]["UpdateParcelRow"] | components["schemas"]["DeleteParcelRow"];
        CreateParcelRow: {
            /**
             * @description Operation type identifier (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            operation: "create";
            /** @description Purpose of the parcel (e.g., "Residential", "Commercial") */
            purpose: string;
            /** @description Status of the parcel purpose (e.g., "Active", "Pending", "Inactive") */
            purposeStatus: string;
            /** @description Name or identifier for the parcel */
            name: string;
            /** @description Optional comments about the parcel */
            comments?: string | null;
            /** @description Optional reference to an associated image */
            imageId?: number | null;
        };
        UpdateParcelRow: {
            /**
             * @description Operation type identifier (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            operation: "update";
            /** @description Primary key of the parcel to update */
            parcelId: number;
            /** @description Purpose of the parcel (optional field for partial updates) */
            purpose?: string;
            /** @description Status of the parcel purpose (optional field for partial updates) */
            purposeStatus?: string;
            /** @description Name or identifier for the parcel (optional field for partial updates) */
            name?: string;
            /** @description Optional comments about the parcel */
            comments?: string | null;
            /** @description Optional reference to an associated image */
            imageId?: number | null;
        };
        DeleteParcelRow: {
            /**
             * @description Operation type identifier (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            operation: "delete";
            /** @description Primary key of the parcel to delete */
            parcelId: number;
        };
        PatchParcelsResponse: {
            /** @description Per-row results indicating success or failure */
            results: components["schemas"]["ParcelRowResult"][];
        };
        ParcelRowResult: {
            /**
             * @description The operation type that was performed
             * @enum {string}
             */
            operation: "create" | "update" | "delete";
            /**
             * @description The parcel ID. For create operations, this is the server-assigned ID.
             *     For update and delete operations, this echoes the requested parcelId.
             */
            parcelId?: number;
            /**
             * @description Outcome of the operation
             * @enum {string}
             */
            status: "success" | "error";
            /**
             * @description Error message if status is "error".
             *     Examples: "Parcel not found", "Validation failed", "Permission denied"
             */
            error?: string;
        };
        ErrorResponse: {
            /** @description Human-readable error message */
            error: string;
            /** @description Additional error details or context */
            details?: string;
            /** @description Unique identifier for this request (useful for debugging) */
            requestId?: string;
        };
        Parcel: {
            /** @description Unique identifier for the parcel (e.g., 3100000) */
            parcelId: number;
            /** @description Legal description of the parcel (e.g., "Lot A, Block 1"). Server-managed read-only field. */
            appellation?: string | null;
            /** @description Statutory action associated with the parcel (e.g., "Create", "Extinguished"). Server-managed read-only field. */
            action?: string | null;
            /** @description Intent of the parcel (e.g., "Road", "DCDB"). Server-managed read-only field. */
            parcelIntent?: string | null;
            /** @description Purpose of the parcel (e.g., "Land Declared Road") */
            purpose?: string | null;
            /** @description Status of the parcel's purpose (e.g., "Current", "Historic") */
            purposeStatus?: string | null;
            /** @description Name or identifier for the parcel */
            name?: string | null;
            /** @description Optional comments about the parcel */
            comments?: string | null;
            /** @description Optional reference to an associated image (e.g., 4100000) */
            imageId?: number | null;
        };
        GetStatutoryActionResponse: {
            /** @description Type/category of the statutory action. */
            statutoryActionType: string;
            /** @description Current lifecycle status of the statutory action. */
            status: string;
            /** @description Identifier for the vesting survey work. */
            surveyWorkIdVesting: number;
            /** @description Gazette publication year associated with the action. */
            gazetteYear: string;
            /** @description Gazette page number. */
            gazettePage: number;
            /** @description Gazette publication type. */
            gazetteType: string;
            /** @description Additional legal basis text for the action. */
            otherLegality: string;
            /**
             * Format: date-time
             * @description Date/time the statutory action was recorded.
             */
            recordedDate: string;
            /** @description Gazette notice identifier. */
            gazetteNoticeId: number;
            /** @description Array of statutory action parcel records */
            parcels: components["schemas"]["Parcel"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getStatutoryAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the statutory action. */
                statActionId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Statutory action and parcel collection retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GetStatutoryActionResponse"];
                };
            };
            /** @description Unauthorized — invalid or missing bearer token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    patchStatutoryAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique identifier of the statutory action. */
                statActionId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchParcelsRequest"];
            };
        };
        responses: {
            /** @description All operations succeeded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatchParcelsResponse"];
                };
            };
            /** @description Partial success — some rows failed */
            207: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatchParcelsResponse"];
                };
            };
            /** @description Bad request — malformed payload or validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable entity — all rows rejected due to semantic errors */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
